apiVersion: v1
kind: Service
metadata:
  name: travis-service
  namespace: {{ .Values.namespace }}
  labels:
    app: travis-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      name: api
    - protocol: TCP
      port: 8081
      name: admin
  selector:
    app: travis-app
