# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicas: 2
  imagePullPolicy: Always

  ports:
    - name: api
      containerPort: 8080
    - name: admin
      containerPort: 8081

service:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      name: api
    - protocol: TCP
      port: 8081
      name: admin

environment:
  consulHost: "consul.consul:8500"
  kvInitFile: "/var/service/consul-kv-init.sh"
